sudo: false
language: scala
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4
  - 2.13.0-M5
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-stubs/publishLocal scalajs-stubs/mimaReportBinaryIssues
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
