name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.10.7", "2.11.12", "2.12.8", "2.13.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - name: Build
        run: sbt "++${{ matrix.scalaversion }}" scalajs-stubs/publishLocal

      # MiMa is not run for the Scala 2.10.x artifact because there is no
      # version of sbt-mima that works with sbt 1.5.x and for Scala 2.10.x.
      - name: MiMa
        if: matrix.scalaversion != '2.10.7'
        run: sbt "++${{ matrix.scalaversion }}" scalajs-stubs/mimaReportBinaryIssues
